# 列车表
DROP TABLE IF EXISTS `train`;
CREATE TABLE `train` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(列车编号)',
  `train_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '列车名称',
  `train_type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '列车类型',
  `train_length` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '列车长度(米)',
  `train_height` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '列车高度(米)',
  `train_width` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '列车宽度(米)',
  `train_weight` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '列车重量(千克)',
  `seat_number` INT NOT NULL DEFAULT 0 COMMENT '载客座位数量',
  `remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='列车表';

# 列车座位表
DROP TABLE IF EXISTS `train_seat`;
CREATE TABLE `train_seat` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(座位编码)',
  `train_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '列车编号',
  `seat_type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '座位类型：A 商务座 B 一等座 C 二等座 D 无座',
  `carriage_number` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '车厢号',
  `row_number` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '排号',
  `seat_number` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '座号',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='列车座位表';

# 列车车站表
DROP TABLE IF EXISTS `train_station`;
CREATE TABLE `train_station` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(车站编号)',
  `station_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '车站名称',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '地址',
  `remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='列车车站表';

# 列车班次表
DROP TABLE IF EXISTS `train_schedule`;
CREATE TABLE `train_schedule` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(班次编号)',
  `train_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '列车编号',
  `from_station_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '起始站编号',
  `to_station_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '终点站编号',
  `departure_time` TIME NOT NULL DEFAULT '00:00:00' COMMENT '出发时刻(时分秒)',
  `running_time` BIGINT NOT NULL DEFAULT 0 COMMENT '运行时长(毫秒数)',
  `remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='列车班次表';

# 列车班次路线表
DROP TABLE IF EXISTS `train_route`;
CREATE TABLE `train_route` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID',
  `schedule_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '班次编号',
  `station_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '车站编号',
  `sort_number` INT NOT NULL DEFAULT 0 COMMENT '序号(起点为1，后续站点加1递增)',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='列车班次路线表';

# 车票SKU表 (每两个相邻站作为SKU，车票跨站时同时购买不同的SKU)
DROP TABLE IF EXISTS `train_ticket_sku`;
CREATE TABLE `train_ticket_sku` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(SKU编号)',
  `schedule_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '班次编号',
  `from_station_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '起始站编号',
  `to_station_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '终点站编号',
  `seat_type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '座位类型：A 商务座 B 一等座 C 二等座 D 无座',
  `price` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '价格(元)',
  `departure_time` TIME NOT NULL DEFAULT '00:00:00' COMMENT '出发时刻(时分秒)',
  `running_time` BIGINT NOT NULL DEFAULT 0 COMMENT '运行时长(毫秒数)',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='车票SKU表';

# 车票库存表 (每天都有独立的库存，相互不影响)
DROP TABLE IF EXISTS `train_ticket_stock`;
CREATE TABLE `train_ticket_stock` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(库存编号)',
  `sku_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'SKU编号',
  `target_date` DATE NOT NULL DEFAULT '1970-01-01' COMMENT '目标日期',
  `stock_in_theory` INT NOT NULL DEFAULT 0 COMMENT '理论库存',
  `stock` INT NOT NULL DEFAULT 0 COMMENT '库存',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='车票库存表';

# 车票订单表
DROP TABLE IF EXISTS `train_ticket_order`;
CREATE TABLE `train_ticket_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID(订单编号)',
  `schedule_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '班次编号',
  `target_date` DATE NOT NULL DEFAULT '1970-01-01' COMMENT '目标日期',
  `seat_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '座位编码',
  `order_status` VARCHAR(32) NOT NULL DEFAULT 'NEW' COMMENT '订单状态：NEW 新建，PAYING 付款中，PAYED 已付款，CANCEL 已取消，DONE 已完成',
  `order_amount` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '订单金额',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='车票订单表';

# 车票订单项表
DROP TABLE IF EXISTS `train_ticket_order_sku`;
CREATE TABLE `train_ticket_order_sku` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '业务ID',
  `order_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '订单编号',
  `sku_biz_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'SKU编号',
  `target_date` DATE NOT NULL DEFAULT '1970-01-01' COMMENT '目标日期',
  `price` DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMMENT '价格(元)',
  `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否有效：0 否，1 是',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0 否，1 是',
  `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB COMMENT='车票订单项表';


# 在有库存的情况下，可以出票，但是怎么分配座位呢？

